source :rubygems
gem "foreman"
gem "thin"
gem "couchrest"
gem "couchrest_model"
gem "css_parser"
gem "haml"
gem "highline"
gem "nokogiri"
gem "sunspot", "~>1.3"
gem "sunspot_rails", "~>1.3"
gem "sunspot_solr", "~>1.3.1", :group => :development
gem "sinatra", :require => "sinatra/base"
gem "sinatra-r18n"
gem "dalli"
gem "newrelic_rpm"
gem "rack"
gem "rack-test"
gem "test-unit"
gem "rake"
gem "escape_utils"
gem "memcachier"
