source "http://rubygems.org"

gem "couchrest"
gem "couchrest_model"
gem "css_parser"
gem "haml"
gem "highline"
gem "indextank"
gem "nokogiri"
gem "sunspot"
gem "sunspot_rails"
gem "sinatra"
gem "sinatra-r18n"
