source "http://rubygems.org"
gem "thin"
gem "couchrest"
gem "couchrest_model"
gem "css_parser"
gem "haml"
gem "highline"
gem "nokogiri"
gem "sunspot", "~>1.3"
gem "sunspot_rails", "~>1.3"
gem "sinatra"
gem "sinatra-r18n"
gem "dalli"
gem "newrelic_rpm"
gem "rack-test"
gem "test-unit"
gem "rake"
